version: '3'

services:
  frontend:
    build: ./recipebuddy/frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage
  backend:
    build: ./recipebuddy/backend 
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage

