name: Build and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPOONACULAR_BASE_URL: ${{ secrets.SPOONACULAR_BASE_URL }}
      SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11
    - name: Install dependencies
      run: |
        chmod +x install_playwright.sh
        ./install_playwright.sh
    - name: Run tests
      run: |
        pytest
