name: Build and Test

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Optional input parameter'
        required: false
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPOONACULAR_BASE_URL: ${{ secrets.SPOONACULAR_BASE_URL }}
      SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r recipebuddy/backend/requirements.txt
        pip install -r recipebuddy/frontend/requirements.txt
        playwright install
    - name: Start FastAPI server
      run: |
        cd recipebuddy/backend
        uvicorn src.recipebuddy_backend.main:app --host 0.0.0.0 --port 8080 &
        sleep 5 # wait for server to start
    - name: Run backend tests
      run: |
        cd recipebuddy/backend/src/recipebuddy_backend
        pytest tests
    - name: Start Streamlit server
      run: |
        cd recipebuddy/frontend
        streamlit run src/recipebuddy_frontend/Recipe_Buddy.py --server.port 8501 &
        sleep 5 # wait for server to start
    - name: Run frontend tests
      run: |
        cd recipebuddy/frontend/src/recipebuddy_frontend
        pytest tests
